# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Dependabot configuration for managing dependencies in the project
version: 2
updates:
  # Update PHP dependencies
  - package-ecosystem: "composer"
    directory: "/" # Root directory for composer.json
    schedule:
      interval: "weekly"

  # Update Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/" # Root directory for package.json
    schedule:
      interval: "weekly"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows" # Directory for GitHub Actions workflows
    schedule:
      interval: "weekly"

